# config.yaml

# Model settings
model_name: 'esm2_t6_8M_UR50D'
num_labels: 2
separator: 'AAAAA'
max_length: 36

# Data settings
train_path: 'datasets/combined_train_bal.csv'
test_path: 'datasets/majority_testing_dataset.csv'

# Training settings
output_dir: 'outputs'
per_device_train_batch_size: 64
per_device_eval_batch_size: 64
num_train_epochs: 50
learning_rate: 0.000005
save_steps: 800
eval_steps: 800

# Wandb settings
wandb_project: 'ESM_Vit_meta'

# Test settings
checkpoint_path: 'model/ESM-ViT_TCR_checkpoint'